In [64]:
# STEP 1: Import necessary packages
import pandas as pd
import os
from functools import lru_cache

# STEP 2: Display pandas version for debugging purposes
print(pd.__version__)

# STEP 3: Function to load and clean the CSV data
@lru_cache(maxsize=None)
def load_and_clean_csv(file_path):
    if not os.path.exists(file_path):
        raise FileNotFoundError(f"The file {file_path} does not exist.")
    
    # STEP 3.1: Load the data
    df = pd.read_csv(file_path)
    
    # STEP 3.2: Define columns to keep
    columns_to_keep = [
        'number_of_reviews',
        'reviews_per_month',
        'minimum_nights',
        'calculated_host_listings_count',
        'review_scores_rating',
        'accommodates',
        'price',
        'availability_365',
        'availability_90',
        'availability_60', 
        'availability_30',
        'room_type',
        'room_class',
        'id',
        'latitude',
        'longitude', 
        'host_id'
    ]
    
    # STEP 3.3: Filter DataFrame based on columns and replace NaNs with pd.NA
    df = df.loc[:, [col for col in columns_to_keep if col in df.columns]].replace([None, ''], pd.NA)

    # STEP 3.4: Check for non-numeric values in 'price', 'latitude', and 'longitude'
    print("\nRows with non-numeric characters in 'price':")
    print(df[~df['price'].str.replace('[\$,]', '', regex=True).apply(lambda x: str(x).replace('.', '', 1).isdigit())])

    print("\nRows with non-numeric characters in 'latitude':")
    print(df[~df['latitude'].apply(lambda x: str(x).replace('.', '', 1).isdigit())])

    print("\nRows with non-numeric characters in 'longitude':")
    print(df[~df['longitude'].apply(lambda x: str(x).replace('.', '', 1).isdigit())])

    # STEP 3.5: Convert relevant columns to numeric (with coercion for errors)
    df['price'] = pd.to_numeric(df['price'].str.replace('[\$,]', '', regex=True), errors='coerce')
    df['latitude'] = pd.to_numeric(df['latitude'], errors='coerce')
    df['longitude'] = pd.to_numeric(df['longitude'], errors='coerce')

    # STEP 3.6: Drop rows with NaNs in essential columns and print the count of deleted rows
    rows_before = df.shape[0]
    numeric_cols = ['price', 'latitude', 'longitude']
    df = df.dropna(subset=numeric_cols)
    print(f"Rows deleted: {rows_before - df.shape[0]}")

    # STEP 3.7: Clean 'price' column if it exists
    if 'price' in df.columns:
        df['price'] = df['price'].astype(str).str.replace('[\$,]', '', regex=True).astype(float)

    # STEP 3.8: Convert other columns to float where applicable
    float_cols = [
        'number_of_reviews', 'reviews_per_month', 'minimum_nights',
        'calculated_host_listings_count', 'review_scores_rating', 'accommodates',
        'availability_365', 'availability_90', 'availability_60', 'availability_30',
        'id', 'latitude', 'longitude', 'host_id'
    ]
    df[float_cols] = df[float_cols].apply(pd.to_numeric, errors='coerce')

    # Print data types after conversion
    print("\nUpdated column data types:")
    print(df.dtypes)

    return df

# STEP 4: Specify the file path for the raw data
file_path = 'Raw data/raw/2020-11-listings.csv'

# STEP 5: Load and clean the data
df = load_and_clean_csv(file_path)

# STEP 6: Display the first few rows of the cleaned data
print("First few rows of the cleaned data:")
print(df.head())

# STEP 7: Compare the types of values in 'room_class' and 'room_type' if they exist,
# and produce a table of values for each column
if 'room_class' in df.columns:
    print("\nRoom Class Values:")
    print(df['room_class'].value_counts())
if 'room_type' in df.columns:
    print("\nRoom Type Values:")
    print(df['room_type'].value_counts())

2.2.2

Rows with non-numeric characters in 'price':
Empty DataFrame
Columns: [number_of_reviews, reviews_per_month, minimum_nights, calculated_host_listings_count, review_scores_rating, accommodates, price, availability_365, availability_90, availability_60, availability_30, room_type, id, latitude, longitude, host_id]
Index: []

Rows with non-numeric characters in 'latitude':
Empty DataFrame
Columns: [number_of_reviews, reviews_per_month, minimum_nights, calculated_host_listings_count, review_scores_rating, accommodates, price, availability_365, availability_90, availability_60, availability_30, room_type, id, latitude, longitude, host_id]
Index: []

Rows with non-numeric characters in 'longitude':
       number_of_reviews  reviews_per_month  minimum_nights  \
0                    192               1.48               7
1                     21               0.17               1
2                     89               0.67              10
3                     42               0.36               4
4                      0                NaN               3
...                  ...                ...             ...
76978                  0                NaN               7
76979                  0                NaN               2
76980                  0                NaN               1
76982                  0                NaN               7
76983                  0                NaN               1

       calculated_host_listings_count  review_scores_rating  accommodates  \
0                                   2                  91.0             4
1                                   2                  97.0             2
2                                   1                  96.0             2
3                                  15                  94.0             6
4                                   2                   NaN             2
...                               ...                   ...           ...
76978                              10                   NaN             1
76979                              10                   NaN             2
76980                               1                   NaN             2
76982                               1                   NaN             2
76983                               1                   NaN             1

         price  availability_365  availability_90  availability_60  \
0       $97.00               279                4                0
1       $40.00               365               90               60
2       $75.00               150               50               20
3      $307.00               330               85               55
4      $150.00               364               89               59
...        ...               ...              ...              ...
76978   $31.00               362               87               57
76979   $90.00               170               80               50
76980   $87.00               173               83               53
76982   $59.00               153               63               33
76983   $44.00                32               32               32

       availability_30        room_type        id  latitude  longitude  \
0                    0  Entire home/apt     11551  51.46225   -0.11732
1                   30     Private room     13913  51.56802   -0.11121
2                    0  Entire home/apt     15400  51.48796   -0.16898
3                   25  Entire home/apt     17402  51.52195   -0.14094
4                   29     Private room     17506  51.47935   -0.19743
...                ...              ...       ...       ...        ...
76978               27     Private room  46258333  51.49723   -0.09065
76979               20  Entire home/apt  46259322  51.51343   -0.13286
76980               23     Private room  46259459  51.50755   -0.15069
76982                3     Private room  46259530  51.49081   -0.20835
76983               20     Private room  46261520  51.58022   -0.13328

         host_id
0          43039
1          54730
2          60302
3          67564
4          67915
...          ...
76978  356855972
76979  356855972
76980  320950254
76982   10505514
76983   22456475

[71592 rows x 16 columns]
Rows deleted: 0

Updated column data types:
number_of_reviews                   int64
reviews_per_month                 float64
minimum_nights                      int64
calculated_host_listings_count      int64
review_scores_rating              float64
accommodates                        int64
price                             float64
availability_365                    int64
availability_90                     int64
availability_60                     int64
availability_30                     int64
room_type                          object
id                                  int64
latitude                          float64
longitude                         float64
host_id                             int64
dtype: object
First few rows of the cleaned data:
   number_of_reviews  reviews_per_month  minimum_nights  \
0                192               1.48               7
1                 21               0.17               1
2                 89               0.67              10
3                 42               0.36               4
4                  0                NaN               3

   calculated_host_listings_count  review_scores_rating  accommodates  price  \
0                               2                  91.0             4   97.0
1                               2                  97.0             2   40.0
2                               1                  96.0             2   75.0
3                              15                  94.0             6  307.0
4                               2                   NaN             2  150.0

   availability_365  availability_90  availability_60  availability_30  \
0               279                4                0                0
1               365               90               60               30
2               150               50               20                0
3               330               85               55               25
4               364               89               59               29

         room_type     id  latitude  longitude  host_id
0  Entire home/apt  11551  51.46225   -0.11732    43039
1     Private room  13913  51.56802   -0.11121    54730
2  Entire home/apt  15400  51.48796   -0.16898    60302
3  Entire home/apt  17402  51.52195   -0.14094    67564
4     Private room  17506  51.47935   -0.19743    67915

Room Type Values:
room_type
Entire home/apt    42209
Private room       33578
Shared room          621
Hotel room           576
Name: count, dtype: int64

In [65]:
# STEP 9:Save the cleaned data to a new CSV file
output_file_path = 'cleaned_2020_data.csv'
df.to_csv(output_file_path, index=False)
print(f"Cleaned data has been saved to '{output_file_path}'.")

Cleaned data has been saved to 'cleaned_2020_data.csv'.

In [67]:
# Specify the new file path for the raw data (2020 data)
file_path_2021 = 'Raw data/raw/2021-10-listings.csv'

# Specify the new output file path for the cleaned 2020 data
output_file_path_2021 = 'cleaned_2021_data.csv'

# Load and clean the 2020 data using the cached function
df_2021 = load_and_clean_csv(file_path_2021)

# Display the first few rows of the cleaned 2020 data
print("First few rows of the cleaned 2021 data:")
print(df_2021.head())

# STEP 7: Compare the types of values in 'room_class' and 'room_type' if they exist,
# and produce a table of values for each column
if 'room_class' in df.columns:
    print("\nRoom Class Values:")
    print(df['room_class'].value_counts())
if 'room_type' in df.columns:
    print("\nRoom Type Values:")
    print(df['room_type'].value_counts())

First few rows of the cleaned 2021 data:
   number_of_reviews  reviews_per_month  minimum_nights  \
0                 21               0.17               1
1                 89               0.80               3
2                 43               0.35               4
3                  0                NaN               3
4                 93               0.77               7

   calculated_host_listings_count  review_scores_rating  accommodates  price  \
0                               2                  4.85             2   65.0
1                               1                  4.79             2   75.0
2                              15                  4.69             6  307.0
3                               2                   NaN             2  150.0
4                               1                  4.89             4  195.0

   availability_365  availability_90  availability_60  availability_30  \
0               359               84               54               24
1               153               63               33               18
2               322               47               23                2
3               364               89               59               29
4               248                6                6                6

         room_type     id  latitude  longitude  host_id
0     Private room  13913  51.56802   -0.11121    54730
1  Entire home/apt  15400  51.48780   -0.16813    60302
2  Entire home/apt  17402  51.52195   -0.14094    67564
3     Private room  17506  51.47935   -0.19743    67915
4  Entire home/apt  24328  51.47298   -0.16376    41759

Room Type Values:
room_type
Entire home/apt    42209
Private room       33578
Shared room          621
Hotel room           576
Name: count, dtype: int64

In [68]:
# STEP 8: Decide if you need to delete a column
if 'room_class' in df.columns:
    df.drop(columns=['room_class'], inplace=True)
    print("Column 'room_class' has been deleted.")

# Save the cleaned 2020 data to a new CSV file
df_2021.to_csv(output_file_path_2021, index=False)
print(f"Cleaned 2021 data has been saved to '{output_file_path_2021}'.")

Cleaned 2021 data has been saved to 'cleaned_2021_data.csv'.

In [69]:
# Specify the new file path for the raw data (2022 data)
file_path_2022 = 'Raw data/raw/2022-09-10-listings.csv'

# Specify the new output file path for the cleaned 2022 data
output_file_path_2022 = 'cleaned_2022_data.csv'

# Load and clean the 2022 data using the cached function
df_2022 = load_and_clean_csv(file_path_2022)

# Display the first few rows of the cleaned 2022 data
print("First few rows of the cleaned 2021 data:")
print(df_2022.head())

# STEP 7: Compare the types of values in 'room_class' and 'room_type' if they exist,
# and produce a table of values for each column
if 'room_class' in df.columns:
    print("\nRoom Class Values:")
    print(df['room_class'].value_counts())
if 'room_type' in df.columns:
    print("\nRoom Type Values:")
    print(df['room_type'].value_counts())

Rows with non-numeric characters in 'price':
Empty DataFrame
Columns: [number_of_reviews, reviews_per_month, minimum_nights, calculated_host_listings_count, review_scores_rating, accommodates, price, availability_365, availability_90, availability_60, availability_30, room_type, id, latitude, longitude, host_id]
Index: []

Rows with non-numeric characters in 'latitude':
Empty DataFrame
Columns: [number_of_reviews, reviews_per_month, minimum_nights, calculated_host_listings_count, review_scores_rating, accommodates, price, availability_365, availability_90, availability_60, availability_30, room_type, id, latitude, longitude, host_id]
Index: []

Rows with non-numeric characters in 'longitude':
       number_of_reviews  reviews_per_month  minimum_nights  \
0                     30               0.20               1
1                     89               0.57               3
2                     42               0.34               5
3                     65               0.47               3
4                     51               0.36               4
...                  ...                ...             ...
69345                 33               0.42               5
69346                 67               0.84               5
69347                 61               0.99               3
69348                  6               1.49               3
69349                  9               0.61               3

       calculated_host_listings_count  review_scores_rating  accommodates  \
0                                   2                  4.90             1
1                                   1                  4.79             2
2                                   1                  4.32             2
3                                   1                  4.84             1
4                                   5                  4.74             6
...                               ...                   ...           ...
69345                               1                  4.16             5
69346                               3                  4.90             1
69347                               1                  4.90             5
69348                               1                  5.00             6
69349                               1                  5.00             2

         price  availability_365  availability_90  availability_60  \
0       $50.00               343               68               38
1       $75.00                70                2                2
2       $90.00               222                1                1
3       $55.00                74                2                2
4      $379.00               249               37               23
...        ...               ...              ...              ...
69345  $104.00                89               89               59
69346   $55.00                 0                0                0
69347  $201.00                 0                0                0
69348  $246.00                 4                0                0
69349  $250.00                 2                2                2

       availability_30        room_type        id  latitude  longitude  \
0                   17     Private room     13913  51.56861   -0.11270
1                    2  Entire home/apt     15400  51.48780   -0.16813
2                    1  Entire home/apt    284532  51.52851   -0.07426
3                    2     Private room    106332  51.52874   -0.05396
4                    8  Entire home/apt     17402  51.52195   -0.14094
...                ...              ...       ...       ...        ...
69345               29  Entire home/apt   9568415  51.48313   -0.01235
69346                0     Private room   9671724  51.48300   -0.01346
69347                0  Entire home/apt  20277958  51.50914   -0.10192
69348                0  Entire home/apt  20512703  51.40571   -0.35325
69349                0  Entire home/apt  49698549  51.41029   -0.35975

        host_id
0         54730
1         60302
2       1481412
3        264345
4         67564
...         ...
69345  49536874
69346  49977905
69347   1132775
69348   1706966
69349  34213667

[63953 rows x 16 columns]
Rows deleted: 0

Updated column data types:
number_of_reviews                   int64
reviews_per_month                 float64
minimum_nights                      int64
calculated_host_listings_count      int64
review_scores_rating              float64
accommodates                        int64
price                             float64
availability_365                    int64
availability_90                     int64
availability_60                     int64
availability_30                     int64
room_type                          object
id                                  int64
latitude                          float64
longitude                         float64
host_id                             int64
dtype: object
First few rows of the cleaned 2021 data:
   number_of_reviews  reviews_per_month  minimum_nights  \
0                 30               0.20               1
1                 89               0.57               3
2                 42               0.34               5
3                 65               0.47               3
4                 51               0.36               4

   calculated_host_listings_count  review_scores_rating  accommodates  price  \
0                               2                  4.90             1   50.0
1                               1                  4.79             2   75.0
2                               1                  4.32             2   90.0
3                               1                  4.84             1   55.0
4                               5                  4.74             6  379.0

   availability_365  availability_90  availability_60  availability_30  \
0               343               68               38               17
1                70                2                2                2
2               222                1                1                1
3                74                2                2                2
4               249               37               23                8

         room_type      id  latitude  longitude  host_id
0     Private room   13913  51.56861   -0.11270    54730
1  Entire home/apt   15400  51.48780   -0.16813    60302
2  Entire home/apt  284532  51.52851   -0.07426  1481412
3     Private room  106332  51.52874   -0.05396   264345
4  Entire home/apt   17402  51.52195   -0.14094    67564

Room Type Values:
room_type
Entire home/apt    42209
Private room       33578
Shared room          621
Hotel room           576
Name: count, dtype: int64

In [70]:
# STEP 8: Decide if you need to delete a column
if 'room_class' in df.columns:
    df.drop(columns=['room_class'], inplace=True)
    print("Column 'room_class' has been deleted.")

In [71]:
# Save the cleaned 2022 data to a new CSV file
df_2022.to_csv(output_file_path_2022, index=False)
print(f"Cleaned 2022 data has been saved to '{output_file_path_2022}'.")

Cleaned 2022 data has been saved to 'cleaned_2022_data.csv'.

In [72]:
# STEP 1: Specify the new file path for the raw data
file_path_2023 = 'Raw data/raw/2023-09-06-listings.csv'

# STEP 2: Specify the new output file path for the cleaned data
output_file_path_2023 = 'cleaned_2023_data.csv'

# STEP 3:  Load and clean the data using the cached function
df_2023 = load_and_clean_csv(file_path_2023)

# STEP 4:  Display the first few rows of the cleaned data
print("First few rows of the cleaned 2023 data:")
print(df_2023.head())

# STEP 5:  Compare the types of values in 'room_class' and 'room_type' if they exist,
# and produce a table of values for each column
if 'room_class' in df.columns:
    print("\nRoom Class Values:")
    print(df['room_class'].value_counts())
if 'room_type' in df.columns:
    print("\nRoom Type Values:")
    print(df['room_type'].value_counts())

/tmp/ipykernel_73321/2591267041.py:16: DtypeWarning: Columns (68) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

Rows with non-numeric characters in 'price':
Empty DataFrame
Columns: [number_of_reviews, reviews_per_month, minimum_nights, calculated_host_listings_count, review_scores_rating, accommodates, price, availability_365, availability_90, availability_60, availability_30, room_type, id, latitude, longitude, host_id]
Index: []

Rows with non-numeric characters in 'latitude':
Empty DataFrame
Columns: [number_of_reviews, reviews_per_month, minimum_nights, calculated_host_listings_count, review_scores_rating, accommodates, price, availability_365, availability_90, availability_60, availability_30, room_type, id, latitude, longitude, host_id]
Index: []

Rows with non-numeric characters in 'longitude':
       number_of_reviews  reviews_per_month  minimum_nights  \
0                    216               1.45               2
1                     38               0.27               5
2                     41               0.26               1
3                     94               0.56               7
5                     54               0.36               3
...                  ...                ...             ...
87941                  0                NaN               2
87942                  0                NaN               3
87943                  0                NaN               1
87944                  0                NaN               1
87945                  0                NaN               1

       calculated_host_listings_count  review_scores_rating  accommodates  \
0                                   1                  4.57             2
1                                   1                  4.82             5
2                                   2                  4.80             1
3                                   1                  4.80             2
5                                   9                  4.76             6
...                               ...                   ...           ...
87941                               2                   NaN             3
87942                               1                   NaN             2
87943                               1                   NaN             7
87944                             170                   NaN            10
87945                               6                   NaN             6

         price  availability_365  availability_90  availability_60  \
0       $42.00               217                0                0
1      $175.00                40               38               18
2       $79.00               360               85               55
3      $150.00                73                7                7
5      $476.00               300               50               26
...        ...               ...              ...              ...
87941  $275.00               239               11               11
87942  $145.00                88               88               58
87943  $160.00                80               80               50
87944  $680.00               364               89               59
87945  $170.00               297               87               57

       availability_30        room_type                  id   latitude  \
0                    0     Private room               92644  51.442010
1                   13  Entire home/apt               93015  51.499930
2                   25     Private room               13913  51.568610
3                    7  Entire home/apt               15400  51.487800
5                   14  Entire home/apt               17402  51.521950
...                ...              ...                 ...        ...
87941                1  Entire home/apt  973781286754517228  51.514860
87942               28  Entire home/apt  973801695874775338  51.459042
87943               22     Private room  973811685656289740  51.406100
87944               29  Entire home/apt  973882998775927897  51.450997
87945               27  Entire home/apt  973895808066047620  51.515970

       longitude    host_id
0      -0.187390     498201
1      -0.217070     499704
2      -0.112700      54730
3      -0.168130      60302
5      -0.140940      67564
...          ...        ...
87941  -0.135980  498408783
87942  -0.055458   36645347
87943  -0.236126  340514057
87944  -0.444319  439074505
87945  -0.111342  475112423

[80926 rows x 16 columns]
Rows deleted: 0

Updated column data types:
number_of_reviews                   int64
reviews_per_month                 float64
minimum_nights                      int64
calculated_host_listings_count      int64
review_scores_rating              float64
accommodates                        int64
price                             float64
availability_365                    int64
availability_90                     int64
availability_60                     int64
availability_30                     int64
room_type                          object
id                                  int64
latitude                          float64
longitude                         float64
host_id                             int64
dtype: object
First few rows of the cleaned 2023 data:
   number_of_reviews  reviews_per_month  minimum_nights  \
0                216               1.45               2
1                 38               0.27               5
2                 41               0.26               1
3                 94               0.56               7
4                180               1.21               4

   calculated_host_listings_count  review_scores_rating  accommodates  price  \
0                               1                  4.57             2   42.0
1                               1                  4.82             5  175.0
2                               2                  4.80             1   79.0
3                               1                  4.80             2  150.0
4                               1                  4.62             2   46.0

   availability_365  availability_90  availability_60  availability_30  \
0               217                0                0                0
1                40               38               18               13
2               360               85               55               25
3                73                7                7                7
4               196                5                5                5

         room_type     id  latitude  longitude  host_id
0     Private room  92644  51.44201   -0.18739   498201
1  Entire home/apt  93015  51.49993   -0.21707   499704
2     Private room  13913  51.56861   -0.11270    54730
3  Entire home/apt  15400  51.48780   -0.16813    60302
4     Private room  93734  51.47618    0.01442   497514

Room Type Values:
room_type
Entire home/apt    42209
Private room       33578
Shared room          621
Hotel room           576
Name: count, dtype: int64

In [73]:
# STEP 1: Specify the new file path for the raw data
file_path_2021 = 'Raw data/raw/2021-10-listings.csv'

# STEP 2: Specify the new output file path for the cleaned data
output_file_path_2021 = 'cleaned_2021_data.csv'

# STEP 3:  Load and clean the data using the cached function
df_2021 = load_and_clean_csv(file_path_2021)

# STEP 4:  Display the first few rows of the cleaned data
print("First few rows of the cleaned 2021 data:")
print(df_2021.head())

# STEP 5:  Compare the types of values in 'room_class' and 'room_type' if they exist,
# and produce a table of values for each column
if 'room_class' in df.columns:
    print("\nRoom Class Values:")
    print(df['room_class'].value_counts())
if 'room_type' in df.columns:
    print("\nRoom Type Values:")
    print(df['room_type'].value_counts())

##### DECISION REQUIRED
    
# STEP 6: Decide if you need to delete a column
if 'room_class' in df.columns:
    df.drop(columns=['room_class'], inplace=True)
    print("Column 'room_class' has been deleted.")

# STEP 7: Save the cleaned data to a new CSV file
df_2021.to_csv(output_file_path_2021, index=False)
print(f"Cleaned 2021 data has been saved to '{output_file_path_2021}'.")

Cleaned 2023 data has been saved to 'cleaned_2023_data.csv'.